name: sideswap
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+25

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # secure recovery page
  secure_application: ^3.7.3
  animations: ^2.0.0
  another_flushbar: ^1.10.23

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  delayed_display: ^2.0.0
  dotted_line: ^3.0.0
  easy_localization: ^3.0.0
  enum_to_string: ^2.0.1
  # testing only - remove if not used
  faker: ^2.0.0
  ffi: ^1.1.2
  # dynamic links
  firebase_dynamic_links: ^2.0.5
  #firebase notifications
  firebase_messaging: ^10.0.1
  fixnum: ^1.0.0
  # contacts
  flutter_contact: ^0.8.1+2
  # provider
  flutter_hooks: ^0.17.0
  # icon generator
  flutter_launcher_icons: ^0.9.0
  #notifications
  flutter_local_notifications: ^6.0.0
  flutter_plugin_android_lifecycle: ^2.0.2
  # screen scaling
  flutter_screenutil: ^5.0.0+2
  # license loading indicator
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  # switch
  flutter_switch: ^0.3.1
  # mnemonic words suggestions
  flutter_typeahead: ^3.1.3
  # notification payload parsing
  freezed_annotation: ^0.14.2
  # fonts
  google_fonts: ^2.1.0
  hooks_riverpod: ^0.14.0+4
  image: ^3.0.2
  # avatar
  image_picker: ^0.7.5+3
  json_annotation: ^4.0.1
  # logger
  logger: ^1.0.0
  # marqee text
  marquee: ^2.1.0
  package_info: ^2.0.2
  # background
  path_drawing: ^0.5.1
  path_provider: ^2.0.2
  pedantic: ^1.11.0
  # permissions (contacts)
  permission_handler: ^8.0.1
  # pin
  pinput: ^1.2.0
  #provider: ^4.3.2
  protobuf: ^2.0.0
  qr_code_scanner: ^0.4.0
  qr_flutter: ^4.0.0
  # rxdart
  rxdart: ^0.26.0
  share: ^2.0.4
  shared_preferences: ^2.0.6
  # sliding tx list
  sliding_up_panel: ^2.0.0+1
  # deep/app links
  uni_links: ^0.5.1
  url_launcher: ^6.0.6
  # sound notification
  flutter_ringtone_player: ^3.0.0
  vibration: ^1.7.4-nullsafety.0
  move_to_background: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: 1.5.0
  build_runner: ^2.0.4
  freezed: ^0.14.2
  json_serializable: ^4.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - LICENSE
    - assets/licenses/libwally-core-license.txt
    - assets/licenses/gdk-license.txt
    - images/icon_btc.png
    - images/check_mark.svg
    - images/swap.svg
    - assets/wordlist.txt
    - assets/translations/
    - assets/btc_logo.svg
    - assets/usdt_logo.svg
    - assets/lbtc_logo.svg
    - assets/accounts.svg
    - assets/accounts_active.svg
    - assets/home.svg
    - assets/home_active.svg
    - assets/requests.svg
    - assets/requests_active.svg
    - assets/swap.svg
    - assets/swap_active.svg
    - assets/logo.svg
    - assets/settings.svg
    - assets/top_right_arrow.svg
    - assets/bottom_left_arrow.svg
    - assets/qr_code_scan.svg
    - assets/qr_icon.svg
    - assets/filter.svg
    - assets/back_arrow.svg
    - assets/search.svg
    - assets/mini_button.svg
    - assets/tx_peg_in.svg
    - assets/tx_swap.svg
    - assets/share.svg
    - assets/share2.svg
    - assets/share3.svg
    - assets/copy.svg
    - assets/close.svg
    - assets/swap_arrows.svg
    - assets/info.svg
    - assets/error.svg
    - assets/success.svg
    - assets/recovery.svg
    - assets/shield.svg
    - assets/about.svg
    - assets/delete.svg
    - assets/shield_big.svg
    - assets/locker.svg
    - assets/locker2.svg
    - assets/exclamationMark.svg
    - assets/web_icon.svg
    - assets/github_icon.svg
    - assets/twitter_icon.svg
    - assets/telegram_icon.svg
    - assets/avatar.svg
    - assets/associate_phone.svg
    - assets/phone.svg
    - assets/edit.svg
    - assets/user_details.svg
    - assets/male1.svg
    - assets/male2.svg
    - assets/female1.svg
    - assets/device_frame.svg
    - assets/blinded.svg
    - assets/unblinded.svg
    - assets/link.svg
    - assets/network.svg
    - assets/restart.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
