[package]
name = "sideswap_common"
version = "0.1.2"
edition = "2018"

[dependencies]
sideswap_api = { version = "*", path = "../sideswap_api" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
anyhow = "*"
log = "*"
async-tungstenite = { version = "0.9.3", features = ["tokio-runtime", "tokio-rustls"] }
futures = "*"
futures-util = "*"
tokio = { version = "0.2", features = ["macros", "sync", "time", "stream"] }
tungstenite = { version = "*", default-features = false, features = [] }
derive_more = "*"
bitcoin = "0.25"
