appenders:
  stdout:
    kind: console
    encoder:
      # https://docs.rs/log4rs/0.12.0/log4rs/encode/pattern/index.html
      pattern: "{d(%Y-%m-%d %H:%M:%S%.3f)(utc)} {h({l})} {M} {m}{n}"

  file:
    kind: rolling_file
    path: log/sideswap_dealer_example.log
    encoder:
      kind: pattern
      pattern: "{d(%Y-%m-%d %H:%M:%S%.3f)(utc)} {h({l})} {M} {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 100 mb
      roller:
        kind: fixed_window
        pattern: 'log/sideswap_dealer_example.{}.log.gz'
        base: 0
        count: 10


root:
  level: debug
  appenders:
    - stdout
    - file

loggers:
  hyper:
    level: info
